version: 1.21.{build}
os: Visual Studio 2015
environment:
  solution_path: SMHatchingRNGTool.sln
pull_requests:
  do_not_increment_build_number: true
artifacts:
  - path: SMHatchingRNGTool.zip
    name: SMHatchingRNGTool
build:
  project: $(solution_path)
  verbosity: minimal
after_build:
  - ps: 7z a SMHatchingRNGTool.zip .\SMHatchingRNGTool\bin\Debug\SMHatchingRNGTool.exe
